name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: sudo apt-get install -y ssh

      - name: Setup SSH
        run: |
          # Create SSH directory and set permissions like so:
          # ~/.ssh/
          #   private.key (SSH_PRIVATE_KEY)
          #   known_hosts (SSH_KNOWN_HOSTS)
          #   config (SSH config, disables TCPKeepAlive to prevent connection drops during build)
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts
          echo -e "Host *\n    ServerAliveInterval 20\n    TCPKeepAlive no" > ~/.ssh/config
          chmod 644 ~/.ssh/config
          # Start the SSH agent and add the private key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/private.key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
      
      - name: Pull latest code
        run: |
          # Pull the latest code from the repository
          ssh $PROD "cd ~/sfs-widget && git pull"
        env:
          PROD: "daniel@music.songsforsaplings.com"

      - name: Run build script
        run: |
          # Run the build script and copy the output to a log file
          ssh $PROD "./scripts/build.sh | tee -a ~/sfs-widget/env/builds.log"
        env:
          PROD: "daniel@music.songsforsaplings.com"
